'use strict';
module.exports = {
    fullNotesList : ['C','C#','Db','D','D#','Eb','E','F','F#','Gb','G','G#','Ab','A','A#','Bb','B'],
    notesOrder : {
        'Cbb':-2,
        'Cb':-1,
        'C':0,
        'C#':1,
        'C##':2,
        'Dbb':0,
        'Db':1,
        'D':2,
        'D#':3,
        'D##':4,
        'Ebb':2,
        'Eb':3,
        'E':4,
        'E#':5,
        'E##':6,
        'Fbb':3,
        'Fb':4,
        'F':5,
        'F#':6,
        'F##':7,
        'Gbb':5,
        'Gb':6,
        'G':7,
        'G#':8,
        'G##':9,
        'Abb':7,
        'Ab':8,
        'A':9,
        'A#':10,
        'A##':11,
        'Bbb':9,
        'Bb':10,
        'B':11,
        'B#':12,
        'B##':13
    },
    wholeNotesOrder : {
        'C':1,
        'D':2,
        'E':3,
        'F':4,
        'G':5,
        'A':6,
        'B':7
    },
    letterToName : {
        A:'La',
        B:'Si',
        C:'Do',
        D:'Re',
        E:'Mi',
        F:'Fa',
        G:'Sol'
    },
    nameToLetter : {
        'La':'A',
        'Si':'B',
        'Do':'C',
        'Re':'D',
        'Mi':'E',
        'Fa':'F',
        'Sol':'G'
    },
    intervalQualityDict : {
        m: "minor",
        M: "major",
        P: "perfect",
        A: "augmented",
        d: "diminished",
        $: "magical"
    },
    intervalNumberDict : {
        1: "unison",
        2: "second",
        3: "third",
        4: "fourth",
        5: "fifth",
        6: "sixth",
        7: "seventh",
        8: "octave",
        9: "ninth",
        10: "tenth",
        11: "eleventh",
        12: "twelfth",
        13: "thirteenth",
        14: "fourteenth",
        15: "fifteenth",
    },
    intervalsDict : {
        'A0': 12,
        'P1': 0,
        'd2': 0,
        'm2': 1,
        'A1': 1,
        'M2': 2,
        'd3': 2,
        'm3': 3,
        'A2': 3,
        'M3': 4,
        'd4': 4,
        'P4': 5,
        'A3': 5,
        'd5': 6,
        'A4': 6,
        'P5': 7,
        'd6': 7,
        'm6': 8,
        'A5': 8,
        'M6': 9,
        'd7': 9,
        'm7': 10,
        'A6': 10,
        'M7': 11,
        'd8': 11,
        'P8': 12,
        'A7': 12,
        'A8': 13
    },
    chordsDict : {
        'Major': ['M3','P5'],

        'Minor': ['m3','P5'],
        'm': ['m3','P5'],

        'Augmented': ['M3','A5'],
        'aug': ['M3','A5'],
        '+': ['M3','A5'],

        'Dimished': ['m3','D5'],
        'dim': ['m3','D5'],
        '°': ['m3','D5'],

        'SuspendedFourth': ['P4','P5'],
        'sus4': ['P4','P5'],
        'SuspendedSecond': ['M2','P5'],
        'sus2': ['M2','P5'],

        'MinorSixth': ['m3','P5','M6'],
        'm6': ['m3','P5','M6'],
        'MajorSixth': ['M3','P5','M6'],
        '6': ['M3','P5','M6'],
        'SixthAddNinth': ['M3','P5','M6','M9'],
        '6add9': ['M3','P5','M6','M9'],
        'Ninth': ['M3','P5','m7','M9'],
        '9': ['M3','P5','m7','M9'],
        'MinorNinth': ['m3','P5','m7','M9'],
        'm9': ['m3','P5','m7','M9'],
        'MajorNinth': ['M3','P5','M7','M9'],
        'm9': ['M3','P5','M7','M9'],

        'DominantSeventh': ['M3','P5','m7'],
        '7': ['M3','P5','m7'],
        'MinorSeventh': ['m3','P5','m7'],
        'm7': ['m3','P5','m7'],
        'MajorSeventh': ['M3','P5','M7'],
        'M7': ['M3','P5','M7'],

        'AugmentedDominantSeventh': ['M3','A5','m7'],
        'aug7': ['M3','A5','m7'],
        '+7': ['M3','A5','m7'],
        'AugmentedMinorSeventh': ['m3','A5','m7'],
        'augm7': ['m3','A5','m7'],
        '+m7': ['m3','A5','m7'],
        'AugmentedMajorSeventh': ['M3','A5','M7'],
        'augM7': ['M3','A5','M7'],
        '+M7': ['M3','A5','M7'],

        //dimished 7s
        'DiminishedSeventh': ['m3','d5','d7'],
        'dim7': ['m3','d5','d7'],
        '°7': ['m3','d5','d7'],
        // half dimished
        'MinorSeventhFlatFifth': ['m3','d5','m7'],
        'HalfDiminishedSeventh': ['m3','d5','m7'],
        'm7b5': ['m3','d5','m7'],
        'ø': ['m3','d5','m7'],
    },
    A4Freq:440
}

