'use strict';
module.exports = {
    fullNotesList: ['C', 'C#', 'Db', 'D', 'D#', 'Eb', 'E', 'F', 'F#', 'Gb', 'G', 'G#', 'Ab', 'A', 'A#', 'Bb', 'B'],
    midiNotesList: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
    notesOrder: {
        'Cbb': -2,
        'Cb': -1,
        'C': 0,
        'C#': 1,
        'C##': 2,
        'Cx': 2,
        'Dbb': 0,
        'Db': 1,
        'D': 2,
        'D#': 3,
        'D##': 4,
        'x': 4,
        'Ebb': 2,
        'Eb': 3,
        'E': 4,
        'E#': 5,
        'E##': 6,
        'Ex': 6,
        'Fbb': 3,
        'Fb': 4,
        'F': 5,
        'F#': 6,
        'F##': 7,
        'Fx': 7,
        'Gbb': 5,
        'Gb': 6,
        'G': 7,
        'G#': 8,
        'G##': 9,
        'Gx': 9,
        'Abb': 7,
        'Ab': 8,
        'A': 9,
        'A#': 10,
        'A##': 11,
        'Ax': 11,
        'Bbb': 9,
        'Bb': 10,
        'B': 11,
        'B#': 12,
        'B##': 13,
        'Bx': 13
    },
    wholeNotesOrder: {
        'C': 1,
        'D': 2,
        'E': 3,
        'F': 4,
        'G': 5,
        'A': 6,
        'B': 7
    },
    letterToName: {
        A: 'la',
        B: 'si',
        C: 'do',
        D: 're',
        E: 'mi',
        F: 'fa',
        G: 'sol'
    },
    nameToLetter: {
        'la': 'A',
        'si': 'B',
        'do': 'C',
        're': 'D',
        'mi': 'E',
        'fa': 'F',
        'sol': 'G'
    },
    intervalQualityDict: {
        m: "minor",
        M: "major",
        P: "perfect",
        A: "augmented",
        d: "diminished",
        $: "magical"
    },
    intervalNumberDict: {
        1: "unison",
        2: "second",
        3: "third",
        4: "fourth",
        5: "fifth",
        6: "sixth",
        7: "seventh",
        8: "octave",
        9: "ninth",
        10: "tenth",
        11: "eleventh",
        12: "twelfth",
        13: "thirteenth",
        14: "fourteenth",
        15: "fifteenth",
    },
    intervalsDict: {
        'A0': 12,
        'm0': 10,
        'M0': 11,
        'd0': 9,
        'P1': 0,
        'd2': 0,
        'm2': 1,
        'A1': 1,
        'M2': 2,
        'd3': 2,
        'm3': 3,
        'A2': 3,
        'M3': 4,
        'd4': 4,
        'P4': 5,
        'A3': 5,
        'd5': 6,
        'A4': 6,
        'P5': 7,
        'd6': 7,
        'm6': 8,
        'A5': 8,
        'M6': 9,
        'd7': 9,
        'm7': 10,
        'A6': 10,
        'M7': 11,
        'd8': 11,
        'P8': 12,
        'A7': 12,
        'A8': 13
    },
    scalesDict: {
        //5 notes
        majorpentatonic: ['P1', 'M2', 'M3', 'P5', 'M6'],
        pentatonic: ['P1', 'M2', 'M3', 'P5', 'M6'],
        minorpentatonic: ['P1', 'm3', 'P4', 'P5', 'm7'],
        //6 notes
        blues: ['P1', 'm3', 'P4', 'd5', 'P5', 'm7'],
        wholetone: ['P1', 'M2', 'M3', 'A4', 'A5', 'A6'],
        augmented: ['P1', 'm3', 'M3', 'P5', 'A5', 'M7'],
        promotheus: ['P1', 'M2', 'M3', 'A4', 'M6', 'm7'],
        tritone: ['P1', 'm2', 'M2', 'A4', 'P5', 'm7'],
        //7 notes
        major: ['P1', 'M2', 'M3', 'P4', 'P5', 'M6', 'M7'],
        minor: ['P1', 'M2', 'm3', 'P4', 'P5', 'm6', 'm7'],
        melodicminor: ['P1', 'M2', 'm3', 'P4', 'P5', 'M6', 'M7'],
        harmonicminor: ['P1', 'M2', 'm3', 'P4', 'P5', 'm6', 'M7'],
        harmonicmajor: ['P1', 'M2', 'M3', 'P4', 'P5', 'm6', 'M7'],
        doubleharmonic: ['P1', 'm2', 'M3', 'P4', 'P5', 'm6', 'M7'],

        ionian: ['P1', 'M2', 'M3', 'P4', 'P5', 'M6', 'M7'],
        dorian: ['P1', 'M2', 'm3', 'P4', 'P5', 'M6', 'm7'],
        phrygian: ['P1', 'm2', 'm3', 'P4', 'P5', 'm6', 'm7'],
        lydian: ['P1', 'M2', 'M3', 'A4', 'P5', 'M6', 'M7'],
        mixolydian: ['P1', 'M2', 'M3', 'P4', 'P5', 'M6', 'm7'],
        aeolian: ['P1', 'M2', 'm3', 'P4', 'P5', 'm6', 'm7'],
        locrian: ['P1', 'm2', 'm3', 'P4', 'd5', 'm6', 'm7'],

        enigmatic: ['P1', 'm2', 'M3', 'A4', 'A5', 'A6', 'M7'],
        halfdimished: ['P1', 'M2', 'm3', 'P4', 'd5', 'm6', 'm7'],
        hungarianminor: ['P1', 'M2', 'm3', 'A4', 'P5', 'm6', 'm7'],

        //8 notes
        octatonic: ['P1', 'm2', 'm3', 'M3', 'A4', 'P5', 'M6', 'm7'],
        diminished: ['P1', 'M2', 'm3', 'P4', 'A4', 'A5', 'M6', 'M7'],
        //12 notes
        chromatic: ['P1', 'm2', 'M2', 'm3', 'M3', 'P4', 'A4', 'P5', 'm6', 'M6', 'm7', 'M7'],

    },
    A4Freq: 440,
    scaleTones: {
        1: 'tonic',
        2: 'supertonic',
        3: 'mediant',
        4: 'subdominant',
        5: 'dominant',
        6: 'submediant',
        7: 'leadingNote',
    }
}

